//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.DataTable {
    
    
    public class AutoDataTable {
        
        public const string Menu = "Menu";
        
        public const string OrderScript = "OrderScript";
        
        public const string IngredientTable = "IngredientTable";
        
        public const string SpecialDate = "SpecialDate";
    }
}
