//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.DataTable {
    
    
    [System.SerializableAttribute()]
    public class IngredientTableRow : DataTableRow {
        
        public string Name;
        
        public string Taste;
        
        public string Description;
        
        public float PowderColor_r;
        
        public float PowdeColor_g;
        
        public float PowdeColor_b;
    }
}
