//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.DataTable {
    
    
    [System.SerializableAttribute()]
    public class MenuRow : DataTableRow {
        
        public string Name;
        
        public string Description;
        
        public int Ingredient1;
        
        public int Ingredient2;
    }
}
