//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.DataTable {
    
    
    [System.SerializableAttribute()]
    public class OrderScriptRow : DataTableRow {
        
        public string Name;
        
        public string OrderScript_front;
        
        public string OrderScript_back;
        
        public string Ment1;
        
        public string Ment2;
        
        public string Ment3;
        
        public string Ment4;
        
        public string Ment5;
        
        public string Correct;
        
        public string Wrong;
    }
}
