//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.DataTable {
    
    
    [System.SerializableAttribute()]
    public class SpecialDateRow : DataTableRow {
        
        public string Name;
        
        public int Date1;
        
        public int Date2;
        
        public int Date3;
        
        public int Date4;
        
        public int Date5;
        
        public int Date6;
        
        public int Date7;
        
        public int Date8;
        
        public int Date9;
    }
}
